### ISSUE TITLE
超级大的建议和问题

### ISSUE THREAD

**Issue by CCDC321** [Xposed-Modules-Repo/vn.kwaiching.tao#1]
大哥，这个支持的VPN软件你倒是分享出来呀，找的太难了，github上面贴的三个链接也找不到支持的VPN软件！！

**Comment by SNOQNC** [comment]
解压密码？

**Comment by CCDC321** [comment]
大哥你在说什么...不是密码，是支持破解的vpn软件没有下载的途径



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月25日(周五) 晚上10:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Xposed-Modules-Repo/vn.kwaiching.tao] 超级大的建议和问题 (Issue #1)




 
解压密码？

**Comment by Vogadero** [comment]
vpn软件对应的版本太难找了😂

**Comment by kwaiching** [comment]
> 大哥，这个支持的VPN软件你倒是分享出来呀，找的太难了，github上面贴的三个链接也找不到支持的VPN软件！！

網盤other下面
