### ISSUE TITLE
可否破解一下极光vpn

### ISSUE THREAD

**Issue by fangyuan99** [Xposed-Modules-Repo/vn.kwaiching.tao#6]
https://arr003.network/

**Comment by dapeng1989** [comment]
这个是什么鬼？找软件对应版本有点难，发的网盘那个龟速，下载下来还要解压密码！日哦

**Comment by kwaiching** [comment]
V23.01.19

**Comment by Yuchen0120** [comment]
Chinese:https://arr007.network/
English:https://arr009.network/

**Comment by Yuchen0120** [comment]
Chinese:https://arr007.network/
English:https://arr009.network/
